PortfolioApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	resources :projects, only: [:index, :new, :create]
 root 'projects#index'
  get 'home' => 'projects#home'
  get '/about' => 'projects#about'
  get 'projects/new' => 'projects#new'
  post 'projects' => 'projects#create'
  get 'projects/:id/edit' => 'projects#edit', as: :edit_project
  patch '/projects/:id' => 'projects#update'
  delete 'projects/:id/edit' => 'projects#destroy', as: :destroy_project
  get 'signup' => 'users#new'
  get 'users' => 'users#index'
  get 'users/:id/edit' => 'users#edit', as: :edit_user
  patch '/users/:id' => 'users#update'
  delete 'users/:id/edit' => 'users#destroy', as: :destroy_user

  resources :users
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users do
    member do
      get :confirm_email
    end
  end
  
end

PortfolioApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

PortfolioApp/app/models/project.rb
class Project < ApplicationRecord
	#mount_uploader :image, ImageUploader
	#validates_presence_of :title, presence: true

	mount_uploader :image, ImageUploader


end

PortfolioApp/app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	#VALID_EMAIL_REGEX = /\A[\W+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 30}, uniqueness: true
				#format: {with: VALID_EMAIL_REGEX}
	validates :password, presence: true, length: {minimum: 7}
	before_create :confirmation_token

	def editor?
		self.role == 'editor'
	end

	def admin?
		self.role == 'admin'
	end

	def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(:validate => false)
  	end

	private
	def confirmation_token
      if self.confirm_token.blank?
          self.confirm_token = SecureRandom.urlsafe_base64.to_s
      end
    end
end

PortfolioApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user


  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
  	redirect_to '/login' unless current_user
  end

  def require_editor
  	redirect_to '/' unless current_user.editor? | current_user.admin?
  end

  def require_admin
    redirect_to '/' unless current_user.admin?
  end
  
end

PortfolioApp/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :require_user, only: [:new, :create, :edit, :update, :destroy ]
	before_action :require_editor, only: [:new, :create, :edit, :update, :destroy]
	before_action :require_admin, :require_editor, only: [:new, :create, :edit, :update, :destroy]

	def index
		@projects = Project.all
	end

	def home
	end

	def about
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)
		if @project.save
			flash[:success] = "#{@project.title} has been uplaoded"
			redirect_to '/'
		else
			flash[:error] = "uplaod unsuccessful please make sure file has valid extension"
			render 'new'
		end
	end

	def edit
		@project = Project.find(params[:id])
	end

	def update
		@project = Project.find(params[:id])
		if @project.update_attributes(project_params)
			flash[:success] = "#{@project.title} has been updated"
			redirect_to(:action => 'index')
		else
			flash[:error] = "Update unsuccessful please make sure your file has valid extension"
			render 'edit'
		end
	end

	def destroy
		@project = Project.find(params[:id])
		@project.destroy
		flash[:success] = "#{@project.title} has been deleted"
		redirect_to(:action => 'index')
	end

private
	def project_params
		params.require(:project).permit(:title, :description, :image)
	end
end

PortfolioApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		@user = User.find_by_email(params[:session][:email])
		if @user && @user.authenticate(params[:session][:password])
			if @user.email_confirmed
			session[:user_id] = @user.id
        	redirect_to '/home'
      		else
        	flash.now[:error] = 'Please activate your account by following the 
        	instructions in the account confirmation email you received to proceed'
        	render 'new'
      		end
 
		else
			flash.now[:error] = 'Invalid email/password combination'
			redirect_to '/login'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have been successfuly loged out"
		redirect_to ''
	end

	
end

PortfolioApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :require_admin, only: [:index, :edit, :update, :destroy]

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			ApplicationMailer.registration_confirmation(@user).deliver
        	flash[:success] = "A link has been sent to your email address please click link to confirm"

			redirect_to '/login'
		else
			flash[:error] = "Ooooppss, something went wrong!"
			redirect_to '/signup'
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			flash[:success] = "#{@user.first_name} #{@user.last_name} account has been updated"
			redirect_to(:action => 'index')
		else
			render 'edit'
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:success] = "#{@user.first_name} #{@user.last_name} account has been deleted"
		redirect_to(:action => 'index')
	end

	def confirm_email
    user = User.find_by_confirm_token(params[:id])
    if user
      user.email_activate
      flash[:success] = "Welcome to Bubah's Porfolio page! Your email has been confirmed.
      Please sign in to continue."
      redirect_to '/login'
    else
      flash[:error] = "Sorry. User does not exist please signup again"
      redirect_to root_url
    end
end
	
private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :role, :email_confirmed)
	end

end

PortfolioApp/app/helpers/application_helper.rb
module ApplicationHelper
end

PortfolioApp/app/helpers/projects_helper.rb
module ProjectsHelper
end

PortfolioApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

PortfolioApp/app/helpers/users_helper.rb
module UsersHelper
end

PortfolioApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>PortfolioApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
        </button>
        <a class="navbar-brand" href="/home">Portfolio</a>
      </div>

      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li><a href="/home">Home</a></li>
          <li><a href="/about">About</a></li>
          <li><a href="/">Gallery</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
        
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>

            <li><%= link_to " Logout", logout_path, method: "delete", class: "glyphicon glyphicon-log-out white-link" %></a></li>

            <% if current_user && current_user.admin? %>
            <li><%= link_to " Users", users_path, class: "glyphicon glyphicon-user" %></li>
            <% end %>

          <% else %>
            <li><%= link_to " Login", 'login', class: "glyphicon glyphicon-log-in white-link" %></a></li>
            <li><%= link_to " Sign Up", 'signup', class: "glyphicon glyphicon-user word-tenthpt-sp" %></a></li>
          <% end %>
        </ul>
      </div>
  
    </div>
  </nav>
     <div class="container-fluid text-center">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <% debug(params) if Rails.env.development? %>
  </div>
    <%= yield %>

    <div class="container-fluid bg-4 text-center">
    <p>Bootstrap Theme Made By <a href="https://www.w3schools.com">www.w3schools.com</a></p> 
    </div>

  </body>
</html>

PortfolioApp/app/views/projects/about.html.erb
<div class="container-fluid bg-1 text-center">
  <h3>About Me</h3>
  <img src="C:\Users\conte\Desktop\Bubah.jpg" class="img-circle home-img" alt="Bubah">
  <h3>I grew up in in NYC in the one an only Bronx. My parents are immigrants who migrated to the bronx in 1988 to search for better opportunities for themselfs and their children. Growing up in the bronx has made me the person I am today. Although i was exposed to alot of negatvity i was able to avoid them as a youn adolescent and the enviroment has helped me grow thick skin and become mentaly though youngman. I have no one to thank other than God and my parents. What my mom had to go through every morning to keep in school was nothing short of amazing. Every moring she would wake us up one by one and make sure we took showers and, dress us up and school and the ones who did not reach the age of school to daycare is nothing short of remarkable.</h3>
</div>

PortfolioApp/app/views/projects/edit.html.erb
<div class="project">
	<div class="container">
	

		<%= form_for(@project, :url => {:action => 'update'}) do |f| %>		
			<%= f.text_field :title %>
			<%= f.text_field :description %>
			<br><br>
			<%= f.file_field :image %>
			<%= f.submit "Update", class: "btn btn-success" %>
		<% end %>

	</div>
</div>

PortfolioApp/app/views/projects/home.html.erb
 <div class="bubah-jumbo text-center">
    <div class="container">
      <h1>Welcome To My Website</h1>
      <p>Your imagination will never Lead you to the impossible. Only your doubt will!</p>
      <a href="/about" class="btn btn-primary">Read More</a>
    </div>
 </div>

 <div class="container-fluid bg-1 text-center">
  <h3>Who Am I?</h3>
  <img src="C:\Users\conte\Desktop\Bubah.jpg" class="img-circle home-img" alt="Bubah">
  <h3>My name is Bubah Conteh. I am a Reader, a thinker a creator!</h3>
</div>

<div class="container-fluid bg-2 text-center height-300">
  <h3>My life Goal?</h3>
  <p class="width-500 margin-center">To constantly improve the quality of life for the people closes to me and in my community by utilizing skills and blessing that where granted to me. I am always searcing for problems in my commmunity and working towars creating a solution to remove that problem.</p>
</div>

<div class="container-fluid bg-3 text-center height-300">
  <h3>Where To Find Me?</h3>
	<div class="row">
	<div class="col-sm-4"> 
      <p>Parents Birth place The Gambia.</p>
      <img src="C:\Users\conte\Desktop\gambia.jpg" class="home-img2" alt="Image">
    </div>
    <div class="col-sm-4">
      <p>HomeTown New York City.</p>
      <img src="C:\Users\conte\Desktop\NYC.jpg" class="home-img2" alt="Image">
    </div>
    <div class="col-sm-4">
      <p>Currently Living in Hartford.</p>
      <img src="C:\Users\conte\Desktop\CT.jpg" class="home-img2" alt="Image">
    </div>
    
  </div>
</div>

PortfolioApp/app/views/projects/index.html.erb
<div class="container-fluid bg-3 text-center">
<h3>My Work</h3>
<div class="row text-left">
<br><br>
	<% @projects.each do |project| %>
	<div class="col-sm-4">
		<div class="thumbnail text-center width-450">
		<h3 class="title text-left leftmargin-5"><%= project.title %></h3>
		<p class="image"><%= image_tag project.image.url if project.image? %></p>
		<p class="description text-left width-400 leftmargin-5"><%= project.description %></p>
		<% if current_user && (current_user.editor? | current_user.admin?) %>
		<button class="btn btn-warning text-left leftmargin-5"><%= link_to 'Edit', edit_project_path(project) %></button>
		<button class="btn btn-danger text-left"><%= link_to 'Delete', destroy_project_path(project), :method => :delete %></button>
		<% end %>
		</div>

	</div>
	<% end %>
</div>
	<br>
	<br>
<div>
	<% if current_user && (current_user.editor? | current_user.admin?) %>
	<button class="text-center btn btn-success"><%= link_to 'New Project', "projects/new" %></button>
	<% end %>
</div>

</div>

PortfolioApp/app/views/projects/new.html.erb
<%= form_for(@project) do |f| %>
	<div class="field">
		<%= f.text_area :title, :placeholder => "Title" %><br>
		<%= f.text_area :description, :placeholder => "Description" %><br><br>
		<%= f.file_field :image %><br>
	</div>
	<div class="action">
		<%= f.submit "Create", class: "btn btn-success" %>
	</div>
<% end %>

PortfolioApp/app/views/users/edit.html.erb
<div class="user">
	<div class="container">
	

		<%= form_for(@user, :url => {:action => 'update'}) do |f| %>		
			<%= f.text_field :first_name, :placeholder => 'First name' %>
			<%= f.text_field :last_name, :placeholder => 'Last name' %>
			<%= f.text_field :email, :placeholder => 'Email' %>
			<%= f.text_field :password, :placeholder => 'Password' %>
			<%= f.text_field :role, :placeholder => 'Role' %>
			<%= f.check_box :email_confirmed %><label>Confirm Email</label>
			<%= f.submit "Update", class: "btn btn-success" %>
		<% end %>

	</div>
</div>

PortfolioApp/app/views/users/index.html.erb
<div class="container">

<table class="table table-striped table-bordered table-hover table-condensed">
<tr class="info">
	<th>First Name</th>
	<th>Last Name</th>
	<th>Email</th>
	<th>Role</th>
	<th>Token</th>
	<th>Email Confirmed</th>
	<th>Action</th>
</tr>
<% @users.each do |user| %>
<tr>
	<td><%= user.first_name %></td>
	<td><%= user.last_name %></td>
	<td><%= user.email %></td>
	<td><%= user.role %></td>
	<td><%= user.confirm_token %></td>
	<td><%= user.email_confirmed %></td>
	<% if current_user && (current_user.editor? | current_user.admin?) %>
	<td><button class="btn btn-warning glyphicon glyphicon-edit"><%= link_to ' ', edit_user_path(user) %></button>
	<button class="btn btn-danger glyphicon glyphicon-trash"><%= link_to ' ', destroy_user_path(user), :confirm => 'Are you sure you want to delete user?', :method => :delete %></button></td>
</tr>
	<% end %>

</div>
<% end %>
</table>
</div>

PortfolioApp/app/views/users/new.html.erb
<div class="container">
	<h1>Sign up</h1>

	<%= form_for(@user) do |f| %>
		<div class="form-group">
		<%= f.text_field :first_name, :placeholder => "First name", class: "form-control" %>
		</div>
		<div class="form-group">
		<%= f.text_field :last_name, :placeholder => "Last name", class: "form-control" %>
		</div>
		<div class="form-group">
		<%= f.email_field :email, :placeholder => "Email", class: "form-control" %>
		</div>
		<div class="form-group">
		<%= f.password_field :password, :placeholder => "Password", class: "form-control" %>
		</div>
		<%= f.submit "submit", class: "btn btn-success" %>
	<% end %>
</div>